{% set name = "cnmfsns" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cnmfsns-{{ version }}.tar.gz
  sha256: 10eda05712851baddc0467ca3fa25008f75d7de19104567b44c77afca8f0704b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - cnmfsns = cnmfsns.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }}
    - anndata >=0.8.0
    - pandas
    - numpy
    - scipy >=1.9.0
    - matplotlib-base
    - upsetplot
    - httplib2
    - tomli
    - tomli-w
    - distinctipy
    - click
    - pygraphviz
    - python-igraph
    - pyyaml
    - scikit-learn
    - scanpy
    - fastcluster
    - seaborn
    - statsmodels
    - networkx

test:
  imports:
    - cnmfsns
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MorrissyLab/cNMF-SNS
  summary: 'cNMF-SNS: Consensus Non-negative Matrix Factorization Solution Network Space'
  description: powerful factorization-based multi-omics integration toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - verheytb
