{% set name = "cnmfsns" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cnmfsns-{{ version }}.tar.gz
  sha256: 4f7bd305fcd2d00d7b917b77bf70a48aeec46bd3af8c0d60c0417277ce9d3485

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - cnmfsns = cnmfsns.cli:cli

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - pip
  run:
    - python >=3.9
    - anndata >=0.8.0
    - pandas
    - numpy
    - scipy >=1.9.0
    - matplotlib-base
    - upsetplot
    - httplib2
    - tomli
    - tomli-w
    - distinctipy
    - click
    - pygraphviz
    - python-igraph
    - semantic_version
    - pyyaml
    - scikit-learn
    - scanpy
    - fastcluster

test:
  imports:
    - cnmfsns
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MorrissyLab/cNMF-SNS
  summary: 'cNMF-SNS: Consensus Non-negative Matrix Factorization Solution Network Space'
  description: powerful factorization-based multi-omics integration toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - verheytb
